# Generated by Django 4.1 on 2022-09-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choises',
            new_name='Choice',
        ),
    ]
