# Generated by Django 4.1 on 2022-09-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_choises_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choices',
        ),
    ]
