# Generated by Django 4.1 on 2022-09-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_rename_choices_choises'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choises',
            new_name='Choice',
        ),
    ]
